### ISSUE TITLE
How to prevent combinations of the same master appearing right beside each other?

### ISSUE THREAD

**Issue by banool** [JobiJoba/dolphhinsr_dart#12]
Hi,

Currently if I have a master with two combinations, `nextCard` invariably returns each of the combinations of each master in order. Instead I'd rather it jump between different masters + combinations. The way it is now, users see combination 0,1 and then immediately see combination 1,0, which makes the second card obviously way too easy.

I can look into making a PR with some configuration on the `DolphinSR` object / the `nextCard` method that does this.

**Comment by JobiJoba** [comment]
Hey, 

Sorry I'm not really maintaining the repo anymore as I didn't program in dart for a bit of time now (Focus on other stuff) 

If you want to make PR I'll review them and merge.

**Comment by banool** [comment]
I found a way to make this work without modifying the library itself:
```
  // For each master + combination in random order, seed a review with an
  // increasing timestamp near the epoch with Rating.Again. This way, ignoring
  // the effect of other reviews added after, the masters will come out in a random
  // order. I use MapEntry just because of the absence of a pair / tuple type.
  List<MapEntry<String, Combination>> mastersEntries = [];
  for (Master m in masters) {
    for (Combination c in m.combinations!) {
      mastersEntries.add(MapEntry(m.id!, c));
    }
  }
  mastersEntries.shuffle();
  List<Review> seedReviews = [];
  int epoch = 1000000;
  for (MapEntry<String, Combination> e in mastersEntries) {
    seedReviews.add(Review(
        master: e.key,
        combination: e.value,
        ts: DateTime.fromMillisecondsSinceEpoch(epoch),
        rating: Rating.Again));
    epoch += 10000000;
  }
  dolphin.addReviews(seedReviews);
```
After this you apply any reviews you loaded from storage.
